apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.username | default "postgres" }}
  password: {{ .Values.password | default "postgres" }}
