apiVersion: apps/v1
kind: Deployment
metadata:
  name: qip-ui
  labels:
    app: qip-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qip-ui
  template:
    metadata:
      labels:
        app: qip-ui
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/routes.conf
              subPath: routes.conf
      volumes:
        - name: nginx-config
          configMap:
            name: qip-ui-nginx-conf