apiVersion: v1
data:
  CONSUL_ADMIN_TOKEN: 556339d5-f6a3-ff3b-ce1d-98e5b70d4a13
  CONSUL_URL: http://{{ .Release.Name }}-consul:8500
  NAMESPACE: {{ .Release.Namespace }}
  OPENSEARCH_HOST: {{ .Release.Name }}-opensearch
  OPENSEARCH_PORT: "9200"
  POSTGRES_URL: {{ .Release.Name }}-postgres:5432/{{ .Values.global.postgres.database | default "postgres" }}
  TRACING_ENABLED: "false"
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}-env
  name: {{ .Release.Name }}-env
